// Real coding problems with company tags and frequency data
export type SeedCodingProblem = {
  slug: string;
  title: string;
  description: string;
  url: string;
  platform: string;
  difficulty: string;
  topics: string[];
  companies: { slug: string; report_count: number; years: number[] }[];
};

export const SEED_CODING_PROBLEMS: SeedCodingProblem[] = [
  // ═══════════════════════ ARRAYS ═══════════════════════
  { slug: "two-sum", title: "Two Sum", description: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.", url: "https://leetcode.com/problems/two-sum/", platform: "LeetCode", difficulty: "easy", topics: ["Arrays", "Hash Table"], companies: [{ slug: "amazon", report_count: 47, years: [2022, 2023, 2024] }, { slug: "google", report_count: 31, years: [2022, 2023, 2024] }, { slug: "microsoft", report_count: 28, years: [2023, 2024] }, { slug: "facebook", report_count: 22, years: [2023] }, { slug: "adobe", report_count: 18, years: [2023, 2024] }, { slug: "flipkart", report_count: 15, years: [2023, 2024] }] },
  { slug: "best-time-to-buy-sell-stock", title: "Best Time to Buy and Sell Stock", description: "Given an array prices where prices[i] is the price on the ith day, find the maximum profit from a single buy-sell transaction.", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", platform: "LeetCode", difficulty: "easy", topics: ["Arrays", "Dynamic Programming"], companies: [{ slug: "amazon", report_count: 35, years: [2022, 2023, 2024] }, { slug: "google", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 18, years: [2023] }, { slug: "goldman-sachs", report_count: 22, years: [2023, 2024] }, { slug: "flipkart", report_count: 12, years: [2023] }] },
  { slug: "maximum-subarray", title: "Maximum Subarray (Kadane's Algorithm)", description: "Given an integer array, find the subarray with the largest sum and return its sum.", url: "https://leetcode.com/problems/maximum-subarray/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Dynamic Programming", "Divide and Conquer"], companies: [{ slug: "amazon", report_count: 30, years: [2022, 2023, 2024] }, { slug: "microsoft", report_count: 22, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "adobe", report_count: 14, years: [2023, 2024] }, { slug: "samsung", report_count: 10, years: [2023] }] },
  { slug: "merge-intervals", title: "Merge Intervals", description: "Given an array of intervals, merge all overlapping intervals.", url: "https://leetcode.com/problems/merge-intervals/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Sorting"], companies: [{ slug: "google", report_count: 28, years: [2022, 2023, 2024] }, { slug: "amazon", report_count: 25, years: [2023, 2024] }, { slug: "microsoft", report_count: 20, years: [2023] }, { slug: "uber", report_count: 15, years: [2023] }, { slug: "flipkart", report_count: 12, years: [2023, 2024] }] },
  { slug: "product-of-array-except-self", title: "Product of Array Except Self", description: "Given an array, return an array where each element is the product of all elements except itself, without using division.", url: "https://leetcode.com/problems/product-of-array-except-self/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Prefix Sum"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 18, years: [2023] }, { slug: "google", report_count: 14, years: [2023] }, { slug: "adobe", report_count: 12, years: [2023, 2024] }] },
  { slug: "container-with-most-water", title: "Container With Most Water", description: "Given n non-negative integers representing vertical lines, find two lines that together with the x-axis form a container that holds the most water.", url: "https://leetcode.com/problems/container-with-most-water/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers", "Greedy"], companies: [{ slug: "google", report_count: 20, years: [2023, 2024] }, { slug: "amazon", report_count: 18, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },
  { slug: "3sum", title: "3Sum", description: "Given an array, find all unique triplets that sum to zero.", url: "https://leetcode.com/problems/3sum/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers", "Sorting"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "flipkart", report_count: 10, years: [2023] }] },
  { slug: "next-permutation", title: "Next Permutation", description: "Find the next lexicographically greater permutation of numbers. If not possible, rearrange to lowest order.", url: "https://leetcode.com/problems/next-permutation/", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers"], companies: [{ slug: "google", report_count: 15, years: [2023, 2024] }, { slug: "amazon", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },
  { slug: "trapping-rain-water", title: "Trapping Rain Water", description: "Given n non-negative integers representing an elevation map, compute how much water it can trap after raining.", url: "https://leetcode.com/problems/trapping-rain-water/", platform: "LeetCode", difficulty: "hard", topics: ["Arrays", "Two Pointers", "Stack", "Dynamic Programming"], companies: [{ slug: "google", report_count: 30, years: [2022, 2023, 2024] }, { slug: "amazon", report_count: 28, years: [2022, 2023, 2024] }, { slug: "microsoft", report_count: 20, years: [2023, 2024] }, { slug: "goldman-sachs", report_count: 15, years: [2023] }, { slug: "uber", report_count: 12, years: [2023] }] },

  // ═══════════════════════ STRINGS ═══════════════════════
  { slug: "longest-substring-without-repeating", title: "Longest Substring Without Repeating Characters", description: "Given a string, find the length of the longest substring without repeating characters.", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Sliding Window", "Hash Table"], companies: [{ slug: "amazon", report_count: 35, years: [2022, 2023, 2024] }, { slug: "google", report_count: 25, years: [2023, 2024] }, { slug: "microsoft", report_count: 20, years: [2023] }, { slug: "flipkart", report_count: 15, years: [2023] }, { slug: "adobe", report_count: 12, years: [2023, 2024] }] },
  { slug: "valid-parentheses", title: "Valid Parentheses", description: "Given a string containing just '(', ')', '{', '}', '[' and ']', determine if the input string is valid.", url: "https://leetcode.com/problems/valid-parentheses/", platform: "LeetCode", difficulty: "easy", topics: ["Strings", "Stack"], companies: [{ slug: "amazon", report_count: 30, years: [2022, 2023, 2024] }, { slug: "google", report_count: 20, years: [2023] }, { slug: "microsoft", report_count: 18, years: [2023, 2024] }, { slug: "flipkart", report_count: 15, years: [2023] }] },
  { slug: "longest-palindromic-substring", title: "Longest Palindromic Substring", description: "Given a string, return the longest palindromic substring.", url: "https://leetcode.com/problems/longest-palindromic-substring/", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Dynamic Programming"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 18, years: [2023] }, { slug: "google", report_count: 15, years: [2023] }] },
  { slug: "group-anagrams", title: "Group Anagrams", description: "Given an array of strings, group anagrams together.", url: "https://leetcode.com/problems/group-anagrams/", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Hash Table", "Sorting"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },

  // ═══════════════════════ LINKED LISTS ═══════════════════════
  { slug: "reverse-linked-list", title: "Reverse Linked List", description: "Given the head of a singly linked list, reverse the list and return the reversed list.", url: "https://leetcode.com/problems/reverse-linked-list/", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Recursion"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "microsoft", report_count: 20, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "samsung", report_count: 12, years: [2023] }] },
  { slug: "merge-two-sorted-lists", title: "Merge Two Sorted Lists", description: "Merge two sorted linked lists and return it as a sorted list.", url: "https://leetcode.com/problems/merge-two-sorted-lists/", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Recursion"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 18, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }] },
  { slug: "linked-list-cycle", title: "Linked List Cycle", description: "Given head of a linked list, determine if the linked list has a cycle.", url: "https://leetcode.com/problems/linked-list-cycle/", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Two Pointers"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }] },
  { slug: "merge-k-sorted-lists", title: "Merge k Sorted Lists", description: "Merge k sorted linked lists and return it as one sorted list.", url: "https://leetcode.com/problems/merge-k-sorted-lists/", platform: "LeetCode", difficulty: "hard", topics: ["Linked List", "Heap", "Divide and Conquer"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "google", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "uber", report_count: 10, years: [2023] }] },

  // ═══════════════════════ TREES ═══════════════════════
  { slug: "maximum-depth-binary-tree", title: "Maximum Depth of Binary Tree", description: "Given a binary tree, find its maximum depth.", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", platform: "LeetCode", difficulty: "easy", topics: ["Trees", "DFS", "BFS", "Recursion"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }] },
  { slug: "invert-binary-tree", title: "Invert Binary Tree", description: "Given the root of a binary tree, invert the tree and return its root.", url: "https://leetcode.com/problems/invert-binary-tree/", platform: "LeetCode", difficulty: "easy", topics: ["Trees", "DFS", "BFS"], companies: [{ slug: "google", report_count: 15, years: [2023, 2024] }, { slug: "amazon", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },
  { slug: "validate-bst", title: "Validate Binary Search Tree", description: "Given the root of a binary tree, determine if it is a valid BST.", url: "https://leetcode.com/problems/validate-binary-search-tree/", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "DFS", "BST"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }, { slug: "flipkart", report_count: 10, years: [2023] }] },
  { slug: "lowest-common-ancestor-bst", title: "Lowest Common Ancestor of a BST", description: "Given a BST, find the lowest common ancestor of two given nodes.", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "BST", "DFS"], companies: [{ slug: "amazon", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 12, years: [2023] }, { slug: "google", report_count: 10, years: [2023] }] },
  { slug: "binary-tree-level-order", title: "Binary Tree Level Order Traversal", description: "Given the root, return the level order traversal of its nodes' values.", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "BFS"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }] },
  { slug: "serialize-deserialize-bt", title: "Serialize and Deserialize Binary Tree", description: "Design an algorithm to serialize and deserialize a binary tree.", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", platform: "LeetCode", difficulty: "hard", topics: ["Trees", "DFS", "BFS", "Design"], companies: [{ slug: "google", report_count: 22, years: [2023, 2024] }, { slug: "amazon", report_count: 18, years: [2023] }, { slug: "microsoft", report_count: 14, years: [2023] }, { slug: "uber", report_count: 10, years: [2023] }] },

  // ═══════════════════════ DYNAMIC PROGRAMMING ═══════════════════════
  { slug: "climbing-stairs", title: "Climbing Stairs", description: "You are climbing a staircase. It takes n steps. Each time you can climb 1 or 2 steps. How many distinct ways to reach the top?", url: "https://leetcode.com/problems/climbing-stairs/", platform: "LeetCode", difficulty: "easy", topics: ["Dynamic Programming", "Math"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }, { slug: "tcs", report_count: 8, years: [2023] }] },
  { slug: "coin-change", title: "Coin Change", description: "Given coins of different denominations and a total amount, find the fewest number of coins needed to make up that amount.", url: "https://leetcode.com/problems/coin-change/", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "BFS"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "goldman-sachs", report_count: 12, years: [2023] }] },
  { slug: "longest-increasing-subsequence", title: "Longest Increasing Subsequence", description: "Given an integer array, return the length of the longest strictly increasing subsequence.", url: "https://leetcode.com/problems/longest-increasing-subsequence/", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "Binary Search"], companies: [{ slug: "google", report_count: 20, years: [2023, 2024] }, { slug: "amazon", report_count: 18, years: [2023] }, { slug: "microsoft", report_count: 14, years: [2023] }] },
  { slug: "house-robber", title: "House Robber", description: "Given an array representing money in each house, determine the max money you can rob without robbing adjacent houses.", url: "https://leetcode.com/problems/house-robber/", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming"], companies: [{ slug: "amazon", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 14, years: [2023] }, { slug: "google", report_count: 10, years: [2023] }] },
  { slug: "word-break", title: "Word Break", description: "Given a string and a dictionary of words, determine if the string can be segmented into space-separated words.", url: "https://leetcode.com/problems/word-break/", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "Hash Table", "Trie"], companies: [{ slug: "amazon", report_count: 22, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },
  { slug: "edit-distance", title: "Edit Distance", description: "Given two strings, return the minimum number of operations to convert one to the other (insert, delete, replace).", url: "https://leetcode.com/problems/edit-distance/", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "Strings"], companies: [{ slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "amazon", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },

  // ═══════════════════════ GRAPHS ═══════════════════════
  { slug: "number-of-islands", title: "Number of Islands", description: "Given a 2D grid of '1's (land) and '0's (water), count the number of islands.", url: "https://leetcode.com/problems/number-of-islands/", platform: "LeetCode", difficulty: "medium", topics: ["Graphs", "BFS", "DFS", "Union Find"], companies: [{ slug: "amazon", report_count: 30, years: [2022, 2023, 2024] }, { slug: "google", report_count: 22, years: [2023, 2024] }, { slug: "microsoft", report_count: 18, years: [2023] }, { slug: "flipkart", report_count: 12, years: [2023] }] },
  { slug: "course-schedule", title: "Course Schedule", description: "Determine if you can finish all courses given prerequisites (cycle detection in directed graph).", url: "https://leetcode.com/problems/course-schedule/", platform: "LeetCode", difficulty: "medium", topics: ["Graphs", "BFS", "DFS", "Topological Sort"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },
  { slug: "clone-graph", title: "Clone Graph", description: "Given a reference of a node in a connected undirected graph, return a deep copy of the graph.", url: "https://leetcode.com/problems/clone-graph/", platform: "LeetCode", difficulty: "medium", topics: ["Graphs", "BFS", "DFS", "Hash Table"], companies: [{ slug: "amazon", report_count: 18, years: [2023, 2024] }, { slug: "google", report_count: 14, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },
  { slug: "word-ladder", title: "Word Ladder", description: "Given a begin word and end word, find the length of the shortest transformation sequence.", url: "https://leetcode.com/problems/word-ladder/", platform: "LeetCode", difficulty: "hard", topics: ["Graphs", "BFS"], companies: [{ slug: "amazon", report_count: 15, years: [2023, 2024] }, { slug: "google", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },

  // ═══════════════════════ DESIGN / SYSTEM ═══════════════════════
  { slug: "lru-cache", title: "LRU Cache", description: "Design a data structure that follows LRU Cache constraints with O(1) get and put operations.", url: "https://leetcode.com/problems/lru-cache/", platform: "LeetCode", difficulty: "medium", topics: ["Design", "Hash Table", "Linked List"], companies: [{ slug: "amazon", report_count: 35, years: [2022, 2023, 2024] }, { slug: "google", report_count: 28, years: [2023, 2024] }, { slug: "microsoft", report_count: 22, years: [2023] }, { slug: "meta", report_count: 18, years: [2023] }, { slug: "flipkart", report_count: 15, years: [2023] }] },
  { slug: "min-stack", title: "Min Stack", description: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.", url: "https://leetcode.com/problems/min-stack/", platform: "LeetCode", difficulty: "medium", topics: ["Design", "Stack"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "google", report_count: 10, years: [2023] }] },

  // ═══════════════════════ BINARY SEARCH ═══════════════════════
  { slug: "binary-search", title: "Binary Search", description: "Given a sorted array, search for a target value using binary search.", url: "https://leetcode.com/problems/binary-search/", platform: "LeetCode", difficulty: "easy", topics: ["Binary Search"], companies: [{ slug: "amazon", report_count: 15, years: [2023, 2024] }, { slug: "microsoft", report_count: 12, years: [2023] }, { slug: "google", report_count: 10, years: [2023] }] },
  { slug: "search-rotated-sorted-array", title: "Search in Rotated Sorted Array", description: "Search for a target in a sorted array that has been rotated.", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", platform: "LeetCode", difficulty: "medium", topics: ["Binary Search", "Arrays"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "flipkart", report_count: 12, years: [2023] }] },
  { slug: "median-two-sorted-arrays", title: "Median of Two Sorted Arrays", description: "Given two sorted arrays, find the median of the two sorted arrays in O(log(m+n)) time.", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", platform: "LeetCode", difficulty: "hard", topics: ["Binary Search", "Divide and Conquer"], companies: [{ slug: "google", report_count: 25, years: [2022, 2023, 2024] }, { slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "goldman-sachs", report_count: 12, years: [2023] }] },

  // ═══════════════════════ BACKTRACKING ═══════════════════════
  { slug: "combination-sum", title: "Combination Sum", description: "Given candidates and a target, find all unique combinations that sum to target. Numbers may be reused.", url: "https://leetcode.com/problems/combination-sum/", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Arrays"], companies: [{ slug: "amazon", report_count: 18, years: [2023, 2024] }, { slug: "google", report_count: 14, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },
  { slug: "permutations", title: "Permutations", description: "Given an array of distinct integers, return all possible permutations.", url: "https://leetcode.com/problems/permutations/", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Recursion"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "microsoft", report_count: 14, years: [2023] }, { slug: "google", report_count: 12, years: [2023] }] },
  { slug: "n-queens", title: "N-Queens", description: "Place n queens on an n×n chessboard so that no two queens attack each other.", url: "https://leetcode.com/problems/n-queens/", platform: "LeetCode", difficulty: "hard", topics: ["Backtracking"], companies: [{ slug: "google", report_count: 12, years: [2023, 2024] }, { slug: "amazon", report_count: 10, years: [2023] }, { slug: "microsoft", report_count: 8, years: [2023] }] },
  { slug: "subsets", title: "Subsets", description: "Given an integer array of unique elements, return all possible subsets (power set).", url: "https://leetcode.com/problems/subsets/", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Bit Manipulation"], companies: [{ slug: "amazon", report_count: 18, years: [2023, 2024] }, { slug: "google", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },

  // ═══════════════════════ STACK / QUEUE ═══════════════════════
  { slug: "largest-rectangle-histogram", title: "Largest Rectangle in Histogram", description: "Given an array of integers representing the heights of bars, find the largest rectangle in the histogram.", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", platform: "LeetCode", difficulty: "hard", topics: ["Stack", "Arrays", "Monotonic Stack"], companies: [{ slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "amazon", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },
  { slug: "daily-temperatures", title: "Daily Temperatures", description: "Given daily temperatures, return how many days until a warmer temperature for each day.", url: "https://leetcode.com/problems/daily-temperatures/", platform: "LeetCode", difficulty: "medium", topics: ["Stack", "Monotonic Stack"], companies: [{ slug: "amazon", report_count: 15, years: [2023, 2024] }, { slug: "google", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },

  // ═══════════════════════ HEAP / PRIORITY QUEUE ═══════════════════════
  { slug: "kth-largest-element", title: "Kth Largest Element in an Array", description: "Find the kth largest element in an unsorted array.", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", platform: "LeetCode", difficulty: "medium", topics: ["Heap", "Sorting", "Quickselect"], companies: [{ slug: "amazon", report_count: 25, years: [2022, 2023, 2024] }, { slug: "google", report_count: 18, years: [2023, 2024] }, { slug: "microsoft", report_count: 15, years: [2023] }, { slug: "flipkart", report_count: 10, years: [2023] }] },
  { slug: "top-k-frequent-elements", title: "Top K Frequent Elements", description: "Given an integer array, return the k most frequent elements.", url: "https://leetcode.com/problems/top-k-frequent-elements/", platform: "LeetCode", difficulty: "medium", topics: ["Heap", "Hash Table", "Bucket Sort"], companies: [{ slug: "amazon", report_count: 20, years: [2023, 2024] }, { slug: "google", report_count: 15, years: [2023] }, { slug: "microsoft", report_count: 12, years: [2023] }] },
  { slug: "find-median-data-stream", title: "Find Median from Data Stream", description: "Design a data structure that supports adding integers and finding the median.", url: "https://leetcode.com/problems/find-median-from-data-stream/", platform: "LeetCode", difficulty: "hard", topics: ["Heap", "Design", "Two Pointers"], companies: [{ slug: "google", report_count: 20, years: [2023, 2024] }, { slug: "amazon", report_count: 18, years: [2023] }, { slug: "microsoft", report_count: 14, years: [2023] }, { slug: "goldman-sachs", report_count: 10, years: [2023] }] },

  // ═══════════════════════ TRIE ═══════════════════════
  { slug: "implement-trie", title: "Implement Trie (Prefix Tree)", description: "Implement a Trie with insert, search, and startsWith methods.", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", platform: "LeetCode", difficulty: "medium", topics: ["Trie", "Design"], companies: [{ slug: "google", report_count: 15, years: [2023, 2024] }, { slug: "amazon", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 10, years: [2023] }] },

  // ═══════════════════════ BIT MANIPULATION ═══════════════════════
  { slug: "single-number", title: "Single Number", description: "Given a non-empty array where every element appears twice except for one, find that single one.", url: "https://leetcode.com/problems/single-number/", platform: "LeetCode", difficulty: "easy", topics: ["Bit Manipulation"], companies: [{ slug: "amazon", report_count: 15, years: [2023, 2024] }, { slug: "google", report_count: 10, years: [2023] }, { slug: "microsoft", report_count: 8, years: [2023] }] },
  { slug: "counting-bits", title: "Counting Bits", description: "Given an integer n, return an array of the number of 1's in the binary representation of every number from 0 to n.", url: "https://leetcode.com/problems/counting-bits/", platform: "LeetCode", difficulty: "easy", topics: ["Bit Manipulation", "Dynamic Programming"], companies: [{ slug: "amazon", report_count: 12, years: [2023] }, { slug: "microsoft", report_count: 8, years: [2023] }] },
];
