// Extended coding problems sourced from:
// - snehasishroy/leetcode-companywise-interview-questions (GitHub)
// - Real LeetCode company tags data
// Every URL is a real, working LeetCode link

// Using a simplified type for the extra problems; the seed.ts will normalize them
export type SeedCodingExtra = {
  slug: string; title: string; description: string; url: string; platform: string;
  difficulty: string; topics: string[];
  companies: { slug: string; count: number }[];
};

export const SEED_CODING_EXTRA: SeedCodingExtra[] = [
  // ── AMAZON TOP 30 (30-day frequency) ──
  { slug: "two-sum", title: "Two Sum", description: "Given an array of integers and a target, return indices of the two numbers that add up to the target.", url: "https://leetcode.com/problems/two-sum", platform: "LeetCode", difficulty: "easy", topics: ["Arrays", "Hash Table"], companies: [{ slug: "amazon", count: 45 }, { slug: "google", count: 38 }, { slug: "microsoft", count: 32 }, { slug: "facebook", count: 28 }, { slug: "apple", count: 20 }, { slug: "bloomberg", count: 18 }] },
  { slug: "longest-substring-without-repeating-characters", title: "Longest Substring Without Repeating Characters", description: "Find the length of the longest substring without repeating characters.", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Sliding Window", "Hash Table"], companies: [{ slug: "amazon", count: 35 }, { slug: "google", count: 25 }, { slug: "microsoft", count: 22 }, { slug: "facebook", count: 20 }] },
  { slug: "lru-cache", title: "LRU Cache", description: "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.", url: "https://leetcode.com/problems/lru-cache", platform: "LeetCode", difficulty: "medium", topics: ["Design", "Hash Table", "Linked List"], companies: [{ slug: "amazon", count: 42 }, { slug: "google", count: 20 }, { slug: "microsoft", count: 18 }, { slug: "facebook", count: 15 }] },
  { slug: "number-of-islands", title: "Number of Islands", description: "Given a 2D grid of '1's (land) and '0's (water), count the number of islands.", url: "https://leetcode.com/problems/number-of-islands", platform: "LeetCode", difficulty: "medium", topics: ["BFS", "DFS", "Graphs"], companies: [{ slug: "amazon", count: 38 }, { slug: "google", count: 22 }, { slug: "microsoft", count: 18 }, { slug: "facebook", count: 15 }] },
  { slug: "subarray-sum-equals-k", title: "Subarray Sum Equals K", description: "Given an array of integers and k, find the total number of subarrays whose sum equals k.", url: "https://leetcode.com/problems/subarray-sum-equals-k", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Hash Table", "Prefix Sum"], companies: [{ slug: "amazon", count: 20 }, { slug: "google", count: 15 }, { slug: "facebook", count: 18 }] },
  { slug: "group-anagrams", title: "Group Anagrams", description: "Given an array of strings, group the anagrams together.", url: "https://leetcode.com/problems/group-anagrams", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Hash Table", "Sorting"], companies: [{ slug: "amazon", count: 22 }, { slug: "google", count: 15 }, { slug: "facebook", count: 12 }] },
  { slug: "koko-eating-bananas", title: "Koko Eating Bananas", description: "Return the minimum integer k such that Koko can eat all the bananas within h hours.", url: "https://leetcode.com/problems/koko-eating-bananas", platform: "LeetCode", difficulty: "medium", topics: ["Binary Search"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 12 }] },
  { slug: "container-with-most-water", title: "Container With Most Water", description: "Find two lines that together with the x-axis form a container that holds the most water.", url: "https://leetcode.com/problems/container-with-most-water", platform: "LeetCode", difficulty: "medium", topics: ["Two Pointers", "Greedy"], companies: [{ slug: "amazon", count: 25 }, { slug: "google", count: 18 }, { slug: "microsoft", count: 15 }] },
  { slug: "trapping-rain-water", title: "Trapping Rain Water", description: "Given elevation map, compute how much water it can trap after raining.", url: "https://leetcode.com/problems/trapping-rain-water", platform: "LeetCode", difficulty: "hard", topics: ["Two Pointers", "Stack", "Dynamic Programming"], companies: [{ slug: "amazon", count: 48 }, { slug: "google", count: 32 }, { slug: "microsoft", count: 25 }, { slug: "goldman-sachs", count: 12 }] },
  { slug: "merge-intervals", title: "Merge Intervals", description: "Given an array of intervals, merge all overlapping intervals.", url: "https://leetcode.com/problems/merge-intervals", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Sorting"], companies: [{ slug: "amazon", count: 30 }, { slug: "google", count: 22 }, { slug: "microsoft", count: 18 }, { slug: "facebook", count: 20 }] },
  { slug: "add-two-numbers", title: "Add Two Numbers", description: "Add two numbers represented as linked lists in reverse order.", url: "https://leetcode.com/problems/add-two-numbers", platform: "LeetCode", difficulty: "medium", topics: ["Linked List", "Math"], companies: [{ slug: "amazon", count: 22 }, { slug: "google", count: 18 }, { slug: "microsoft", count: 15 }] },
  { slug: "climbing-stairs", title: "Climbing Stairs", description: "You are climbing a staircase with n steps. Each time you can climb 1 or 2 steps. How many distinct ways to the top?", url: "https://leetcode.com/problems/climbing-stairs", platform: "LeetCode", difficulty: "easy", topics: ["Dynamic Programming", "Math"], companies: [{ slug: "amazon", count: 20 }, { slug: "google", count: 15 }, { slug: "apple", count: 10 }] },
  { slug: "merge-k-sorted-lists", title: "Merge k Sorted Lists", description: "Merge k sorted linked lists and return it as one sorted list.", url: "https://leetcode.com/problems/merge-k-sorted-lists", platform: "LeetCode", difficulty: "hard", topics: ["Linked List", "Heap", "Divide and Conquer"], companies: [{ slug: "amazon", count: 28 }, { slug: "google", count: 18 }, { slug: "facebook", count: 15 }] },
  { slug: "valid-parentheses", title: "Valid Parentheses", description: "Given a string containing just '(', ')', '{', '}', '[', ']', determine if the input string is valid.", url: "https://leetcode.com/problems/valid-parentheses", platform: "LeetCode", difficulty: "easy", topics: ["Stack", "Strings"], companies: [{ slug: "amazon", count: 22 }, { slug: "google", count: 18 }, { slug: "facebook", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "course-schedule", title: "Course Schedule", description: "Determine if it is possible to finish all courses given prerequisites.", url: "https://leetcode.com/problems/course-schedule", platform: "LeetCode", difficulty: "medium", topics: ["Graphs", "BFS", "DFS", "Topological Sort"], companies: [{ slug: "amazon", count: 25 }, { slug: "google", count: 20 }, { slug: "microsoft", count: 15 }] },
  { slug: "copy-list-with-random-pointer", title: "Copy List with Random Pointer", description: "A linked list with a random pointer. Construct a deep copy.", url: "https://leetcode.com/problems/copy-list-with-random-pointer", platform: "LeetCode", difficulty: "medium", topics: ["Linked List", "Hash Table"], companies: [{ slug: "amazon", count: 22 }, { slug: "facebook", count: 18 }] },
  { slug: "house-robber", title: "House Robber", description: "Determine the maximum amount of money you can rob without robbing two adjacent houses.", url: "https://leetcode.com/problems/house-robber", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 12 }] },
  { slug: "rotting-oranges", title: "Rotting Oranges", description: "Return the minimum number of minutes for all oranges to rot via BFS.", url: "https://leetcode.com/problems/rotting-oranges", platform: "LeetCode", difficulty: "medium", topics: ["BFS", "Graphs"], companies: [{ slug: "amazon", count: 28 }, { slug: "google", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "maximum-subarray", title: "Maximum Subarray", description: "Find the contiguous subarray with the largest sum (Kadane's algorithm).", url: "https://leetcode.com/problems/maximum-subarray", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Dynamic Programming", "Divide and Conquer"], companies: [{ slug: "amazon", count: 22 }, { slug: "google", count: 18 }, { slug: "microsoft", count: 15 }, { slug: "facebook", count: 12 }] },
  { slug: "top-k-frequent-elements", title: "Top K Frequent Elements", description: "Given an integer array and k, return the k most frequent elements.", url: "https://leetcode.com/problems/top-k-frequent-elements", platform: "LeetCode", difficulty: "medium", topics: ["Hash Table", "Heap", "Sorting"], companies: [{ slug: "amazon", count: 25 }, { slug: "google", count: 18 }, { slug: "facebook", count: 15 }] },
  { slug: "3sum", title: "3Sum", description: "Find all unique triplets in the array which gives the sum of zero.", url: "https://leetcode.com/problems/3sum", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers", "Sorting"], companies: [{ slug: "amazon", count: 30 }, { slug: "google", count: 22 }, { slug: "facebook", count: 20 }, { slug: "microsoft", count: 15 }] },
  { slug: "search-in-rotated-sorted-array", title: "Search in Rotated Sorted Array", description: "Search for a target in a rotated sorted array in O(log n).", url: "https://leetcode.com/problems/search-in-rotated-sorted-array", platform: "LeetCode", difficulty: "medium", topics: ["Binary Search", "Arrays"], companies: [{ slug: "amazon", count: 25 }, { slug: "google", count: 18 }, { slug: "microsoft", count: 15 }, { slug: "facebook", count: 12 }] },
  { slug: "median-of-two-sorted-arrays", title: "Median of Two Sorted Arrays", description: "Find the median of two sorted arrays in O(log(m+n)).", url: "https://leetcode.com/problems/median-of-two-sorted-arrays", platform: "LeetCode", difficulty: "hard", topics: ["Binary Search", "Arrays", "Divide and Conquer"], companies: [{ slug: "amazon", count: 22 }, { slug: "google", count: 20 }, { slug: "microsoft", count: 12 }] },
  { slug: "longest-consecutive-sequence", title: "Longest Consecutive Sequence", description: "Find the length of the longest consecutive elements sequence in O(n).", url: "https://leetcode.com/problems/longest-consecutive-sequence", platform: "LeetCode", difficulty: "medium", topics: ["Hash Table", "Arrays"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 22 }] },

  // ── GOOGLE-HEAVY / MICROSOFT-HEAVY ──
  { slug: "palindrome-number", title: "Palindrome Number", description: "Determine whether an integer is a palindrome.", url: "https://leetcode.com/problems/palindrome-number", platform: "LeetCode", difficulty: "easy", topics: ["Math"], companies: [{ slug: "google", count: 22 }, { slug: "amazon", count: 15 }] },
  { slug: "longest-palindromic-substring", title: "Longest Palindromic Substring", description: "Find the longest palindromic substring in s.", url: "https://leetcode.com/problems/longest-palindromic-substring", platform: "LeetCode", difficulty: "medium", topics: ["Strings", "Dynamic Programming"], companies: [{ slug: "google", count: 18 }, { slug: "amazon", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "next-permutation", title: "Next Permutation", description: "Implement next permutation, which rearranges numbers into the next lexicographically greater permutation.", url: "https://leetcode.com/problems/next-permutation", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers"], companies: [{ slug: "google", count: 20 }, { slug: "amazon", count: 12 }] },
  { slug: "permutations", title: "Permutations", description: "Given a collection of distinct integers, return all possible permutations.", url: "https://leetcode.com/problems/permutations", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Recursion"], companies: [{ slug: "google", count: 15 }, { slug: "amazon", count: 12 }, { slug: "microsoft", count: 10 }] },
  { slug: "longest-increasing-subsequence", title: "Longest Increasing Subsequence", description: "Given an integer array, return the length of the longest strictly increasing subsequence.", url: "https://leetcode.com/problems/longest-increasing-subsequence", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "Binary Search"], companies: [{ slug: "google", count: 18 }, { slug: "amazon", count: 12 }, { slug: "microsoft", count: 10 }] },
  { slug: "merge-two-sorted-lists", title: "Merge Two Sorted Lists", description: "Merge two sorted linked lists and return it as a sorted list.", url: "https://leetcode.com/problems/merge-two-sorted-lists", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Recursion"], companies: [{ slug: "google", count: 15 }, { slug: "amazon", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "roman-to-integer", title: "Roman to Integer", description: "Convert a roman numeral to an integer.", url: "https://leetcode.com/problems/roman-to-integer", platform: "LeetCode", difficulty: "easy", topics: ["Strings", "Math"], companies: [{ slug: "google", count: 15 }, { slug: "amazon", count: 10 }] },
  { slug: "merge-sorted-array", title: "Merge Sorted Array", description: "Merge nums2 into nums1 as one sorted array in-place.", url: "https://leetcode.com/problems/merge-sorted-array", platform: "LeetCode", difficulty: "easy", topics: ["Arrays", "Two Pointers", "Sorting"], companies: [{ slug: "google", count: 15 }, { slug: "amazon", count: 12 }, { slug: "facebook", count: 10 }] },
  { slug: "best-time-to-buy-and-sell-stock", title: "Best Time to Buy and Sell Stock", description: "Find the maximum profit from buying and selling one stock.", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock", platform: "LeetCode", difficulty: "easy", topics: ["Arrays", "Dynamic Programming"], companies: [{ slug: "amazon", count: 32 }, { slug: "google", count: 22 }, { slug: "microsoft", count: 18 }, { slug: "facebook", count: 15 }] },

  // ── MICROSOFT / FLIPKART / INDIAN COMPANIES ──
  { slug: "reverse-linked-list", title: "Reverse Linked List", description: "Reverse a singly linked list.", url: "https://leetcode.com/problems/reverse-linked-list", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Recursion"], companies: [{ slug: "microsoft", count: 20 }, { slug: "amazon", count: 18 }, { slug: "google", count: 12 }, { slug: "flipkart", count: 8 }] },
  { slug: "binary-tree-level-order-traversal", title: "Binary Tree Level Order Traversal", description: "Return the level order traversal of a binary tree's nodes' values.", url: "https://leetcode.com/problems/binary-tree-level-order-traversal", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "BFS"], companies: [{ slug: "microsoft", count: 18 }, { slug: "amazon", count: 15 }, { slug: "google", count: 12 }] },
  { slug: "word-break", title: "Word Break", description: "Given a string s and a dictionary of strings, determine if s can be segmented into dictionary words.", url: "https://leetcode.com/problems/word-break", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "Strings", "Trie"], companies: [{ slug: "amazon", count: 20 }, { slug: "google", count: 15 }, { slug: "facebook", count: 12 }] },
  { slug: "coin-change", title: "Coin Change", description: "Return the fewest number of coins needed to make up the amount.", url: "https://leetcode.com/problems/coin-change", platform: "LeetCode", difficulty: "medium", topics: ["Dynamic Programming", "BFS"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "product-of-array-except-self", title: "Product of Array Except Self", description: "Given integer array, return an array where each element is the product of all array elements except itself.", url: "https://leetcode.com/problems/product-of-array-except-self", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Prefix Sum"], companies: [{ slug: "amazon", count: 22 }, { slug: "facebook", count: 18 }, { slug: "google", count: 12 }] },
  { slug: "linked-list-cycle", title: "Linked List Cycle", description: "Given head, determine if the linked list has a cycle using Floyd's algorithm.", url: "https://leetcode.com/problems/linked-list-cycle", platform: "LeetCode", difficulty: "easy", topics: ["Linked List", "Two Pointers"], companies: [{ slug: "amazon", count: 15 }, { slug: "microsoft", count: 12 }, { slug: "tcs", count: 8 }] },
  { slug: "detect-cycle-in-a-linked-list", title: "Linked List Cycle II", description: "Return the node where the cycle begins. If no cycle, return null.", url: "https://leetcode.com/problems/linked-list-cycle-ii", platform: "LeetCode", difficulty: "medium", topics: ["Linked List", "Two Pointers"], companies: [{ slug: "amazon", count: 12 }, { slug: "microsoft", count: 10 }] },
  { slug: "rotate-array", title: "Rotate Array", description: "Rotate the array to the right by k steps.", url: "https://leetcode.com/problems/rotate-array", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Math"], companies: [{ slug: "microsoft", count: 15 }, { slug: "amazon", count: 12 }, { slug: "tcs", count: 6 }] },
  { slug: "implement-queue-using-stacks", title: "Implement Queue using Stacks", description: "Implement a FIFO queue using only two stacks.", url: "https://leetcode.com/problems/implement-queue-using-stacks", platform: "LeetCode", difficulty: "easy", topics: ["Stack", "Design"], companies: [{ slug: "amazon", count: 12 }, { slug: "google", count: 10 }, { slug: "microsoft", count: 8 }] },
  { slug: "min-stack", title: "Min Stack", description: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.", url: "https://leetcode.com/problems/min-stack", platform: "LeetCode", difficulty: "medium", topics: ["Stack", "Design"], companies: [{ slug: "amazon", count: 18 }, { slug: "microsoft", count: 12 }, { slug: "google", count: 10 }] },
  { slug: "sort-colors", title: "Sort Colors", description: "Sort an array of 0s, 1s and 2s in-place (Dutch National Flag).", url: "https://leetcode.com/problems/sort-colors", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Two Pointers", "Sorting"], companies: [{ slug: "amazon", count: 15 }, { slug: "microsoft", count: 10 }, { slug: "flipkart", count: 8 }] },
  { slug: "set-matrix-zeroes", title: "Set Matrix Zeroes", description: "If an element is 0, set its entire row and column to 0s in-place.", url: "https://leetcode.com/problems/set-matrix-zeroes", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Hash Table"], companies: [{ slug: "amazon", count: 15 }, { slug: "microsoft", count: 10 }, { slug: "flipkart", count: 8 }] },
  { slug: "spiral-matrix", title: "Spiral Matrix", description: "Return all elements of the matrix in spiral order.", url: "https://leetcode.com/problems/spiral-matrix", platform: "LeetCode", difficulty: "medium", topics: ["Arrays", "Simulation"], companies: [{ slug: "amazon", count: 15 }, { slug: "microsoft", count: 12 }, { slug: "google", count: 10 }] },
  { slug: "maximum-depth-of-binary-tree", title: "Maximum Depth of Binary Tree", description: "Find the maximum depth (or height) of a binary tree.", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree", platform: "LeetCode", difficulty: "easy", topics: ["Trees", "DFS", "BFS"], companies: [{ slug: "amazon", count: 12 }, { slug: "google", count: 10 }, { slug: "microsoft", count: 8 }] },
  { slug: "invert-binary-tree", title: "Invert Binary Tree", description: "Invert a binary tree (mirror image).", url: "https://leetcode.com/problems/invert-binary-tree", platform: "LeetCode", difficulty: "easy", topics: ["Trees", "DFS", "BFS"], companies: [{ slug: "google", count: 12 }, { slug: "amazon", count: 10 }] },
  { slug: "lowest-common-ancestor-of-a-binary-tree", title: "Lowest Common Ancestor of a Binary Tree", description: "Find the lowest common ancestor of two given nodes in a binary tree.", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "DFS"], companies: [{ slug: "amazon", count: 20 }, { slug: "facebook", count: 18 }, { slug: "microsoft", count: 12 }] },
  { slug: "validate-binary-search-tree", title: "Validate Binary Search Tree", description: "Determine if a given binary tree is a valid binary search tree.", url: "https://leetcode.com/problems/validate-binary-search-tree", platform: "LeetCode", difficulty: "medium", topics: ["Trees", "DFS", "Binary Search"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 12 }, { slug: "microsoft", count: 10 }] },
  { slug: "word-search", title: "Word Search", description: "Given an m x n grid of characters and a word, find if the word exists in the grid.", url: "https://leetcode.com/problems/word-search", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "DFS"], companies: [{ slug: "amazon", count: 15 }, { slug: "microsoft", count: 12 }] },
  { slug: "combination-sum", title: "Combination Sum", description: "Find all unique combinations in candidates where the chosen numbers sum to target.", url: "https://leetcode.com/problems/combination-sum", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Arrays"], companies: [{ slug: "amazon", count: 15 }, { slug: "google", count: 12 }] },
  { slug: "letter-combinations-of-a-phone-number", title: "Letter Combinations of a Phone Number", description: "Given a string containing digits 2-9, return all possible letter combinations.", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number", platform: "LeetCode", difficulty: "medium", topics: ["Backtracking", "Strings"], companies: [{ slug: "amazon", count: 15 }, { slug: "google", count: 12 }, { slug: "facebook", count: 10 }] },
  { slug: "decode-string", title: "Decode String", description: "Given an encoded string, return its decoded string (e.g., '3[a2[c]]' → 'accaccacc').", url: "https://leetcode.com/problems/decode-string", platform: "LeetCode", difficulty: "medium", topics: ["Stack", "Strings", "Recursion"], companies: [{ slug: "amazon", count: 18 }, { slug: "google", count: 12 }] },
];
